/**
 * WILSONIX MIDIKEY - Master SoundBank Catalog (single source of truth).
 * Every HD workstation / M1 / Triton / SFX instrument entry that the multi-layer
 * engine, picker UIs and registration manager read from lives here. Import this
 * module (or re-export via multi-layer-engine.js) instead of re-declaring the map.
 */

import { ANIMAL_EDM_BANKS } from "./animal-edm-manifest.js";
import { BLOOM_EDM_BANKS } from "./bloom-edm-manifest.js";
import { MULTISAMPLE_BANKS } from "./multisample-manifest.js";

export const HD_SOUNDBANKS = {
  ...ANIMAL_EDM_BANKS,
  ...BLOOM_EDM_BANKS,
  ...MULTISAMPLE_BANKS,
  acoustic_grand_piano: { id: "acoustic_grand_piano", name: "Velo Piano Concert Grand", category: "Acoustic Piano" },
  electric_piano_1: { id: "electric_piano_1", name: "Triton Suit. & Stage EP", category: "Electric Piano" },
  rhodes_stage_mp3: { id: "rhodes_stage_mp3", name: "Stage Rhodes 73 (Vintage Muir)", category: "Electric Piano" },
  abletunes_fm_piano: { id: "abletunes_fm_piano", name: "Abletunes Studio FM Piano (DX7)", category: "Electric Piano" },
  abletunes_upright: { id: "abletunes_upright", name: "Abletunes Studio Upright Piano", category: "Acoustic Piano" },
  m1_piano_16: { id: "m1_piano_16", name: "Korg M1 Piano 16' (Vogue House)", category: "Acoustic Piano" },
  m1_organ_2: { id: "m1_organ_2", name: "Korg M1 Organ 2 (Show Me Love)", category: "Organ & Bass" },
  m1_universe: { id: "m1_universe", name: "Korg M1 Universe (Celestial Pad)", category: "Synth Pad" },
  m1_ooh_ahh: { id: "m1_ooh_ahh", name: "Korg M1 03 Ooh-Ahh", category: "Strings & Choir" },
  m1_choir: { id: "m1_choir", name: "Korg M1 Ooh-Aah Choir", category: "Strings & Choir" },
  m1_symphonic: { id: "m1_symphonic", name: "Korg M1 Symphonic Strings", category: "Strings" },
  m1_guitar_1: { id: "m1_guitar_1", name: "Korg M1 Guitar 1", category: "Guitar" },
  m1_fretless: { id: "m1_fretless", name: "Korg M1 Fretless Bass", category: "Bass & Sub" },
  m1_pan_flute: { id: "m1_pan_flute", name: "Korg M1 Pan Flute", category: "Woodwind" },
  m1_bottle_bell: { id: "m1_bottle_bell", name: "Korg M1 Bottle Bell", category: "Bells & Mallet" },
  m1_kalimba: { id: "m1_kalimba", name: "Korg M1 Kalimba (Thumb Piano)", category: "Bells & Mallet" },
  kalimba: { id: "kalimba", name: "Acoustic Mbira Kalimba", category: "Bells & Mallet" },
  m1_12string: { id: "m1_12string", name: "Korg M1 12-String", category: "Guitar" },
  m1_fresh_air: { id: "m1_fresh_air", name: "Korg M1 Fresh Air (Airy Bell)", category: "Bells & Pad" },
  m1_slap_bass: { id: "m1_slap_bass", name: "Korg M1 Slap Bass (90s Funk)", category: "Bass & Sub" },
  string_ensemble_1: { id: "string_ensemble_1", name: "Triton Stereo Strings", category: "Strings & Choir" },
  drawbar_organ: { id: "drawbar_organ", name: "Korg M1 / B3 Rock Organ", category: "Organ" },
  alto_sax: { id: "alto_sax", name: "Breathy Alto Saxophone", category: "Woodwind" },
  brass_section: { id: "brass_section", name: "Triton Fat Brass Section", category: "Brass" },
  synth_bass_1: { id: "synth_bass_1", name: "Moog Prodigy Punch Bass", category: "Bass & Sub" },
  distortion_guitar: { id: "distortion_guitar", name: "Triton Distortion Guitar", category: "Guitar" },
  overdriven_guitar: { id: "overdriven_guitar", name: "Heavy Overdrive Guitar", category: "Guitar" },
  electric_guitar_clean: { id: "electric_guitar_clean", name: "Fender Strat Clean Guitar", category: "Guitar" },
  acoustic_guitar_nylon: { id: "acoustic_guitar_nylon", name: "Fantom Acoustic Nylon", category: "Guitar" },
  trumpet: { id: "trumpet", name: "Miles Lead Trumpet", category: "Brass" },
  trombone: { id: "trombone", name: "Tailgate Trombone", category: "Brass" },
  tenor_sax: { id: "tenor_sax", name: "Blue Note Tenor Sax", category: "Woodwind" },
  flute: { id: "flute", name: "Concert Flute", category: "Woodwind" },
  clarinet: { id: "clarinet", name: "Licorice Stick Clarinet", category: "Woodwind" },
  violin: { id: "violin", name: "Solo Violin", category: "Strings & Choir" },
  cello: { id: "cello", name: "Warm Cello", category: "Strings & Choir" },
  choir_aahs: { id: "choir_aahs", name: "Cathedral Choir Aahs", category: "Strings & Choir" },
  church_organ: { id: "church_organ", name: "Cathedral Pipe Organ", category: "Organ" },
  vibraphone: { id: "vibraphone", name: "Cool Vibraphone", category: "Bells & Pad" },
  electric_piano_2: { id: "electric_piano_2", name: "FM Tine EP Second Voice", category: "Electric Piano" },
  acoustic_bass: { id: "acoustic_bass", name: "Upright Walking Bass", category: "Bass & Sub" },
  soprano_sax: { id: "soprano_sax", name: "Sweet Soprano Sax", category: "Woodwind" },
  muted_trumpet: { id: "muted_trumpet", name: "Harmon Mute Trumpet", category: "Brass" },
  acoustic_guitar_steel: { id: "acoustic_guitar_steel", name: "Steel-String Acoustic", category: "Guitar" },
  slap_bass_1: { id: "slap_bass_1", name: "Slap Bass Attack", category: "Bass & Sub" },
  rock_organ: { id: "rock_organ", name: "Rock Organ Shout", category: "Organ" },
  harpsichord: { id: "harpsichord", name: "Baroque Harpsichord", category: "Bells & Pad" },

  // Genuine Saxophone & Reed Instruments
  sax_genuine_solo: { id: "sax_genuine_solo", name: "🎷 Expressive Solo Alto Sax", category: "Woodwind" },
  sax_sensual: { id: "sax_sensual", name: "🎷 Sensual 80s Breathy Sax", category: "Woodwind" },
  sax_blues_growl: { id: "sax_blues_growl", name: "🎷 Dirty Blues Sax Growl", category: "Woodwind" },
  sax_funk_stab: { id: "sax_funk_stab", name: "🎷 Funk Brass & Sax Stab", category: "Woodwind" },
  sax_fall: { id: "sax_fall", name: "🎷 Big Band Sax Fall", category: "Woodwind" },
  sax_scoop: { id: "sax_scoop", name: "🎷 Expressive Pitch Scoop Sax", category: "Woodwind" },

  // Nature Sounds
  nature_thunder: { id: "nature_thunder", name: "Deep Thunder Strike", category: "Nature Sounds" },
  nature_rain: { id: "nature_rain", name: "Gentle Rainstorm Ambience", category: "Nature Sounds" },
  nature_ocean: { id: "nature_ocean", name: "Ocean Surf Waves", category: "Nature Sounds" },
  nature_birds: { id: "nature_birds", name: "Forest Bird Chirps", category: "Nature Sounds" },
  nature_wind: { id: "nature_wind", name: "Howling Wind Gusts", category: "Nature Sounds" },

  // Human Voices
  vox_yeah: { id: "vox_yeah", name: "Vocal Chant 'Yeah!'", category: "Human Voices" },
  vox_whoa: { id: "vox_whoa", name: "Soul Vocal 'Whoa-Oh'", category: "Human Voices" },
  vox_hey: { id: "vox_hey", name: "Hype Vocal 'Hey!'", category: "Human Voices" },
  vox_beatbox: { id: "vox_beatbox", name: "Human Beatbox Kit", category: "Human Voices" },

  // Weird & Sci-Fi FX
  fx_laser: { id: "fx_laser", name: "Laser Beam Zap", category: "Weird & Sci-Fi FX" },
  fx_alien: { id: "fx_alien", name: "Alien Hyperspace Drone", category: "Weird & Sci-Fi FX" },
  fx_bionic: { id: "fx_bionic", name: "Bionic Glitch Cascade", category: "Weird & Sci-Fi FX" },

  // DJ & Cinematic FX
  fx_scratch: { id: "fx_scratch", name: "Vinyl Scratch Cut", category: "DJ & Cinematic FX" },
  fx_tapestop: { id: "fx_tapestop", name: "Tape Stop Slow-Down", category: "DJ & Cinematic FX" },
  fx_subboom: { id: "fx_subboom", name: "Sub Bass Impact Boom", category: "DJ & Cinematic FX" },
  fx_airhorn: { id: "fx_airhorn", name: "Dancehall Reggae Airhorn", category: "DJ & Cinematic FX" },

  // Reggae, Dub & Stage Sound FX
  dub_siren: { id: "dub_siren", name: "🚨 Jamaican Dub Siren", category: "Reggae & Dub SFX" },
  spring_splash: { id: "spring_splash", name: "💥 Vintage Spring Reverb Crash", category: "Reggae & Dub SFX" },
  laser_zap: { id: "laser_zap", name: "⚡ Sound System Laser Zap", category: "Reggae & Dub SFX" },
  dub_horn: { id: "dub_horn", name: "🎺 Dancehall Airhorn Blast", category: "Reggae & Dub SFX" },
  sub_boom: { id: "sub_boom", name: "💣 Heavy 808 Sub-Boom", category: "Reggae & Dub SFX" },
  noise_riser: { id: "noise_riser", name: "🌊 White Noise Sweep Riser", category: "Reggae & Dub SFX" },
  fx_sub_resonator: { id: "fx_sub_resonator", name: "Sub-Atomic Resonator", category: "Weird & Sci-Fi FX" },

  // Human Vocals & Choir
  voice_oohs: { id: "voice_oohs", name: "Soul Gospel Vocal Oohs", category: "Human Voices" },
  vox_yeah_r: { id: "vox_yeah_r", name: "Soul Vocal 'Yeah!' Shout", category: "Human Voices" },
  vox_hey_r: { id: "vox_hey_r", name: "Hype Vocal 'Hey!' Shout", category: "Human Voices" },
  angelic_choir: { id: "angelic_choir", name: "Angelic Worship Choir", category: "Human Voices" },
  vox_hum: { id: "vox_hum", name: "Deep Male Vocal Hum", category: "Human Voices" },

  // Bells & Chimes
  tubular_bells: { id: "tubular_bells", name: "Orchestral Tubular Chimes", category: "Bells & Mallet" },
  wind_chimes: { id: "wind_chimes", name: "Mark Tree Wind Chimes", category: "Bells & Mallet" },
  crystal_chimes: { id: "crystal_chimes", name: "Crystal Shimmer Chimes", category: "Bells & Mallet" },

  // Authentic DJ Samples
  dj_scratch_r: { id: "dj_scratch_r", name: "Authentic Vinyl Scratch", category: "DJ & Cinematic FX" },
  dj_partyhorn_r: { id: "dj_partyhorn_r", name: "Dancehall Reggae Airhorn", category: "DJ & Cinematic FX" },
  dj_siren_r: { id: "dj_siren_r", name: "Sound System Dub Siren", category: "DJ & Cinematic FX" },
  dj_whistle_r: { id: "dj_whistle_r", name: "Carnival Samba Whistle", category: "DJ & Cinematic FX" },

  // Percussions & Drums
  tr808_kit: { id: "tr808_kit", name: "TR-808 Analog Drum Kit", category: "Percussion & Drums" },
  percussion_conga: { id: "percussion_conga", name: "Afro-Cuban Congas (Slap & Open)", category: "Percussion & Drums" },
  synth_drum: { id: "synth_drum", name: "Analog Synth Drum (Simmons SDSV Space)", category: "Percussion & Drums" },
  real_drum_kit: { id: "real_drum_kit", name: "Real Acoustic Drum Kit (Zero-Latency)", category: "Percussion & Drums" },
  percussion_shaker: { id: "percussion_shaker", name: "Latin Shaker & Maracas", category: "Percussion & Drums" },
  taiko_drum: { id: "taiko_drum", name: "Cinematic Taiko Impact", category: "Percussion & Drums" },
  percussion_taiko: { id: "taiko_drum", name: "Cinematic Taiko Impact", category: "Percussion & Drums" },
  // Synthesizer You (Ripped Sounds & Loops)
  sy_surf_spring: { id: "sy_surf_spring", name: "🏄 Synthesizer You - Surf Lead Riff", category: "Synthesizer You (80s)" },
  sy_chorus_swell: { id: "sy_chorus_swell", name: "🎹 Synthesizer You - Juno Chorus Pad Swell", category: "Synthesizer You (80s)" },
  sy_bass_riff: { id: "sy_bass_riff", name: "🎸 Synthesizer You - Analog Bass Riff", category: "Synthesizer You (80s)" },
  sy_gated_snare_1: { id: "sy_gated_snare_1", name: "💥 Synthesizer You - Gated Snare Cannon 1", category: "Synthesizer You (80s)" },
  sy_gated_snare_2: { id: "sy_gated_snare_2", name: "🥁 Synthesizer You - Gated Snare Cannon 2", category: "Synthesizer You (80s)" },
  sy_vox_slap_1: { id: "sy_vox_slap_1", name: "🎤 Synthesizer You - Slapback Vox Shout 1", category: "Synthesizer You (80s)" },
  sy_vox_slap_2: { id: "sy_vox_slap_2", name: "🔥 Synthesizer You - Slapback Vox Shout 2", category: "Synthesizer You (80s)" },
  sy_vox_slap_3: { id: "sy_vox_slap_3", name: "🎶 Synthesizer You - Slapback Vocal Phrase", category: "Synthesizer You (80s)" },
  sy_surf_pluck_c4: { id: "sy_surf_pluck_c4", name: "🎸 Synthesizer You - Surf Pluck C4", category: "Synthesizer You (80s)" },
  sy_kick_punch: { id: "sy_kick_punch", name: "🥊 Synthesizer You - 80s Punch Kick", category: "Synthesizer You (80s)" },
  sy_riser_sweep: { id: "sy_riser_sweep", name: "🚀 Synthesizer You - FX Riser Sweep", category: "Synthesizer You (80s)" },
  sy_tape_drop: { id: "sy_tape_drop", name: "🛑 Synthesizer You - Tape Drop FX", category: "Synthesizer You (80s)" },

  // Roland Legendary D-50, U-20, MV-30 & SC-55 SoundBanks
  roland_d50_fantasia: { id: "roland_d50_fantasia", name: "Roland D-50 Fantasia", category: "Synth Pad" },
  roland_u20_choir: { id: "roland_u20_choir", name: "Roland U-20 Airy Vocal Choir", category: "Strings & Choir" },
  roland_bright_ep: { id: "roland_bright_ep", name: "Roland SA Bright E.Piano", category: "Electric Piano" },
  roland_sc55_warm_pad: { id: "roland_sc55_warm_pad", name: "Roland SC-55 Warm Pad", category: "Synth Pad" },
  roland_space_voice: { id: "roland_space_voice", name: "Roland SC-55 Space Voice", category: "Strings & Choir" },
  roland_metal_pad: { id: "roland_metal_pad", name: "Roland MV-30 Shimmer Metal Pad", category: "Synth Pad" },
  roland_sc55_finger_bass: { id: "roland_sc55_finger_bass", name: "Roland SC-55 Punchy Finger Bass", category: "Bass & Sub" },
  roland_u20_shakuhachi: { id: "roland_u20_shakuhachi", name: "Roland U-20 Breathy Shakuhachi", category: "Woodwind" },
  roland_orchestra_hit: { id: "roland_orchestra_hit", name: "Roland SC-55 Orchestra Hit", category: "Orchestral & Hit" },
  roland_synth_brass: { id: "roland_synth_brass", name: "Roland Jupiter Synth Brass", category: "Brass" },

  // Korg X5D AI2 ROM SoundBanks (Genuine NorCtrack Multisamples)
  x5d_12_string: { id: "x5d_12_string", name: "Korg X5D 12-String Guitar", category: "Guitar" },
  x5d_accordeon: { id: "x5d_accordeon", name: "Korg X5D Musette Accordion", category: "Woodwind" },
  x5d_analog_king: { id: "x5d_analog_king", name: "Korg X5D Analog King (Saw Lead)", category: "Synth Lead" },
  x5d_ancient_sun: { id: "x5d_ancient_sun", name: "Korg X5D Ancient Sun (Ambient Pad)", category: "Synth Pad" },
  x5d_ariana: { id: "x5d_ariana", name: "Korg X5D Ariana (Vocal Air Pad)", category: "Strings & Choir" },
  x5d_bass_horn: { id: "x5d_bass_horn", name: "Korg X5D Bass & Horn Split", category: "Bass & Sub" },
  x5d_big_band: { id: "x5d_big_band", name: "Korg X5D Big Band Horns", category: "Brass" },
  x5d_bigswell: { id: "x5d_bigswell", name: "Korg X5D Big Swell (Strings & Brass)", category: "Orchestral & Hit" },
  x5d_brass_swell: { id: "x5d_brass_swell", name: "Korg X5D Brass Swell", category: "Brass" },
  x5d_cafedral: { id: "x5d_cafedral", name: "Korg X5D Cathedral Pipe Organ", category: "Organ" },
  x5d_chorus_guitar: { id: "x5d_chorus_guitar", name: "Korg X5D Chorus Guitar", category: "Guitar" },
  x5d_chorusclavi: { id: "x5d_chorusclavi", name: "Korg X5D Chorus Clavinet", category: "Keyboard" },
  x5d_crank_it_up: { id: "x5d_crank_it_up", name: "Korg X5D Crank It Up (Dance Lead)", category: "Synth Lead" },
  x5d_crossfades: { id: "x5d_crossfades", name: "Korg X5D Crossfades (Motion Texture)", category: "Synth Pad" },
  x5d_digipiano: { id: "x5d_digipiano", name: "Korg X5D Digi Piano", category: "Acoustic Piano" },
  x5d_east_africa: { id: "x5d_east_africa", name: "Korg X5D East Africa (Mallet)", category: "Bells & Mallet" },
  x5d_etnicorch: { id: "x5d_etnicorch", name: "Korg X5D Ethnic Orchestra", category: "Orchestral & Hit" },
  x5d_fanfare: { id: "x5d_fanfare", name: "Korg X5D Orchestral Fanfare", category: "Brass" },
  x5d_fat_pianos: { id: "x5d_fat_pianos", name: "Korg X5D Fat Layered Pianos", category: "Acoustic Piano" },
  x5d_full_strings: { id: "x5d_full_strings", name: "Korg X5D Full Symphonic Strings", category: "Strings & Choir" },
  x5d_guitarman: { id: "x5d_guitarman", name: "Korg X5D Guitar Man (Solo Electric)", category: "Guitar" },
  x5d_harpsicord: { id: "x5d_harpsicord", name: "Korg X5D Concert Harpsichord", category: "Keyboard" },
  x5d_headhunter: { id: "x5d_headhunter", name: "Korg X5D Headhunter Funk Synth", category: "Synth Lead" },
  x5d_ice_bells: { id: "x5d_ice_bells", name: "Korg X5D Ice Bells (Crystal Shimmer)", category: "Bells & Mallet" },
  x5d_java_bells: { id: "x5d_java_bells", name: "Korg X5D Java Bells (Gamelan Metallic)", category: "Bells & Mallet" },
  x5d_layersynth: { id: "x5d_layersynth", name: "Korg X5D Layer Synth", category: "Synth Pad" },
  x5d_lunar_bells: { id: "x5d_lunar_bells", name: "Korg X5D Lunar Bells", category: "Bells & Mallet" },
  x5d_malguea: { id: "x5d_malguea", name: "Korg X5D Malgueña Flamenco Guitar", category: "Guitar" },
  x5d_maxi_stab: { id: "x5d_maxi_stab", name: "Korg X5D Maxi Orchestra Stab", category: "Orchestral & Hit" },
  x5d_megatron: { id: "x5d_megatron", name: "Korg X5D Megatron Cyber Bass", category: "Bass & Sub" },
  x5d_moonstone: { id: "x5d_moonstone", name: "Korg X5D Moonstone (Celestial Pad)", category: "Synth Pad" },
  x5d_multirez: { id: "x5d_multirez", name: "Korg X5D Multi-Rez Sweep", category: "Synth Lead" },
  x5d_muted_horns: { id: "x5d_muted_horns", name: "Korg X5D Miles Muted Horns", category: "Brass" },
  x5d_neurofunk: { id: "x5d_neurofunk", name: "Korg X5D Neurofunk Bass", category: "Bass & Sub" },
  x5d_newworlds: { id: "x5d_newworlds", name: "Korg X5D New Worlds (Cinematic Pad)", category: "Synth Pad" },
  x5d_phantom_sax: { id: "x5d_phantom_sax", name: "Korg X5D Phantom Tenor Sax", category: "Woodwind" },
  x5d_pizzo: { id: "x5d_pizzo", name: "Korg X5D Pizzicato Strings", category: "Strings & Choir" },
  x5d_rezzofunky: { id: "x5d_rezzofunky", name: "Korg X5D Rezzo Funky Lead", category: "Synth Lead" },
  x5d_rock_organ: { id: "x5d_rock_organ", name: "Korg X5D Rock Organ", category: "Organ" },
  x5d_rock_piano: { id: "x5d_rock_piano", name: "Korg X5D Compressed Rock Piano", category: "Acoustic Piano" },
  x5d_solar_flare: { id: "x5d_solar_flare", name: "Korg X5D Solar Flare (Warm Swell)", category: "Synth Pad" },
  x5d_stereo_keys: { id: "x5d_stereo_keys", name: "Korg X5D Stereo Keys (DX/Rhodes)", category: "Electric Piano" },
  x5d_super_ep: { id: "x5d_super_ep", name: "Korg X5D Super Dyno E.Piano", category: "Electric Piano" },
  x5d_superkeys: { id: "x5d_superkeys", name: "Korg X5D Super Keys (Layer Stack)", category: "Electric Piano" },
  x5d_symphony: { id: "x5d_symphony", name: "Korg X5D Full Classical Symphony", category: "Orchestral & Hit" },
  x5d_the_east: { id: "x5d_the_east", name: "Korg X5D The East (Koto & Shamisen)", category: "Bells & Mallet" },
  x5d_the_saxman: { id: "x5d_the_saxman", name: "Korg X5D The Saxman (Solo Sax)", category: "Woodwind" },
  x5d_the_singers: { id: "x5d_the_singers", name: "Korg X5D The Singers (Vocal Choir)", category: "Strings & Choir" },
  x5d_the_west: { id: "x5d_the_west", name: "Korg X5D The West (Slide Guitar)", category: "Guitar" },
  x5d_torquemada: { id: "x5d_torquemada", name: "Korg X5D Torquemada (Gothic Choir)", category: "Strings & Choir" },
  x5d_ultraperc: { id: "x5d_ultraperc", name: "Korg X5D Ultra World Percussion", category: "Percussion & Drums" },
  x5d_velo_roads: { id: "x5d_velo_roads", name: "Korg X5D Velo Roads Suitcase EP", category: "Electric Piano" },
  x5d_warm_koto: { id: "x5d_warm_koto", name: "Korg X5D Warm Japanese Koto", category: "Bells & Mallet" },
  x5d_warriors: { id: "x5d_warriors", name: "Korg X5D Warriors (Epic Taiko/Horns)", category: "Orchestral & Hit" },
  x5d_wave_guitar: { id: "x5d_wave_guitar", name: "Korg X5D Wave Guitar (Ambient Clean)", category: "Guitar" },
  x5d_wind_orch: { id: "x5d_wind_orch", name: "Korg X5D Symphonic Woodwinds", category: "Woodwind" },
  x5d_x_strings: { id: "x5d_x_strings", name: "Korg X5D X-Strings (Lush AI2 Slow)", category: "Strings & Choir" },
  x5d_x_brass: { id: "x5d_x_brass", name: "Korg X5D X-Brass (Punchy 90s Synth)", category: "Brass" },
  x5d_zen_garden: { id: "x5d_zen_garden", name: "Korg X5D Zen Garden (Flute & Bells)", category: "Bells & Mallet" },
};